<a href="https://colab.research.google.com/github/ToVanLuan/Lab_ML/blob/main/Lab1_21130438_ToVanLuan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
n=int(input("enter n: "))
L=[]
for i  in range(n):

  num=int(input(" Enter num:  "))
  L.append(num)
print("max:",max(L))




enter n: 4
 Enter num:  10
 Enter num:  890
 Enter num:  20
 Enter num:  50
max: 890


In [ ]:
n=int(input("enter n: "))
sum=0
a=1
if n>0:
 for i in range(1,n+1):
  a=a*i
  sum+=a
 print(sum)
else: print("n phai >0")


enter n: 0
k hop le


In [ ]:
class Account:
   def __init__(self, name, email, country, friends=None, posts=None):
     self.name = name
     self.email = email
     self.country = country
     self.friends = friends if friends is not None else []
     self.posts = posts if posts is not None else []

class VerifiedAccount(Account):
   def __init__(self, name, email,fromDate, country, friends=None, posts=None):
    super().__init__( name, email, country, friends, posts)
    self.fromDate=fromDate

class NormalProduct(Account):
   pass

class Post:
   def __init__(self, content, subject, like):
     self.content = content
     self.subject = subject
     self.like = like

class AccountManager:
    def __init__(self, accounts=None):
        self.accounts = accounts if accounts is not None else []

    def getMaxLikePostByFriend(self):
        maxLike = 0
        accountMaxLike = None
        for account in self.accounts:
            for friend in account.friends:
                for post in friend.posts:
                    if post.like > maxLike:
                        maxLike = post.like
                        accountMaxLike = account
        if maxLike > 0:
            return accountMaxLike
        else:
            return None

    def groupAccountsByPostLike(self):
        grouped = {"true": [],"false": []}
        for account in self.accounts:
            if len(account.posts) >= 10:
                key = "true"
            else:
                key = "false"
            grouped[key].append(account)
        return grouped

    def filterAccounts(self, country: str):
        filterAccount=[]
        for account in self.accounts:
            if account.country==country:
                filterAccount.append(account)
        filterAccount.sort(key=lambda x: len(x.posts), reverse=False)
        filterAccount.sort(key=lambda x: x.name, reverse=True)
        return filterAccount
  # Test contructor
post1 = Post("Content 1", "Subject 1", 5)
post2 = Post("Content 2", "Subject 2", 12)
post3 = Post("Content 3", "Subject 3", 8)
account1 = Account("User 1", "user1@gmail.com", "Vietnam", [], [post1, post2])
account2 = Account("User 2", "user2@gmail.com", "Vietnam", [account1], [post3])
account3 = Account("User 3", "user3@gmail.com", "Vietnam", [account2], [post2,post1, post3])
verified_account = VerifiedAccount("Verified User", "verified@gmail.com", "2023-01-01", "Vietnam")
manager = AccountManager([account1, account2, account3, verified_account])
 # Test Method
maxLikeAccount = manager.getMaxLikePostByFriend()
if maxLikeAccount:
    print("Tài khoản có bài đăng được bạn bè thích nhiều nhất là:", maxLikeAccount.name)
else:
    print("Không có tài khoản nào có bài đăng được bạn bè thích.")
grouped_accounts = manager.groupAccountsByPostLike()
print("Tài khoản có ít nhất 10 bài đăng:")
for account in grouped_accounts["true"]:
    print(account.name)
print("Tài khoản có ít hơn 10 bài đăng:")
for account in grouped_accounts["false"]:
    print(account.name)

filtered_accounts=manager.filterAccounts("Vietnam")
print("Các tài khoản ở Việt Nam được sắp xếp theo số bài đăng (tăng dần) và tên (giảm dần):")
for account in filtered_accounts:
    print(account.name)






Tài khoản có bài đăng được bạn bè thích nhiều nhất là: User 2
Tài khoản có ít nhất 10 bài đăng:
Tài khoản có ít hơn 10 bài đăng:
User 1
User 2
User 3
Verified User
Các tài khoản ở Việt Nam được sắp xếp theo số bài đăng (tăng dần) và tên (giảm dần):
Verified User
User 3
User 2
User 1


In [ ]:
import numpy as np
array=np.arange(10,26)
print(array)
reversed_array=array[::-1]
print(reversed_array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
[25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
import numpy as np
arr=np.arange(1,5)
print("Original array: ",arr)
print("Repeating 2 times: ",np.tile(arr,2))
print("Repeating 3 times: ",np.tile(arr,3))


Original array:  [1 2 3 4]
Repeating 2 times:  [1 2 3 4 1 2 3 4]
Repeating 3 times:  [1 2 3 4 1 2 3 4 1 2 3 4]


In [ ]:
import numpy as np
arr=np.array([[0.42, 0.48, 0.32],
                     [0.74, 0.58, 0.38],
                     [0.51, 0.34, 0.15]])
print(arr)
print("Replace all elements of the original array with .5 for values which are greater than .5")
arr[arr>0.5]=0.5
print("result: ")
print(arr)

[[0.42 0.48 0.32]
 [0.74 0.58 0.38]
 [0.51 0.34 0.15]]
Replace all elements of the original array with .5 for values which are greater than .5
result: 
[[0.42 0.48 0.32]
 [0.5  0.5  0.38]
 [0.5  0.34 0.15]]
